### ISSUE TITLE
Deleting Entities with DELETE HTTP Method Endpoints Appears to Currently Not Be Possible

### ISSUE THREAD

**Issue by briankalwat** [Triumph-Tech/Triumph-Helix#1]
### Description

Currently it's possible to create a lava application endpoint that uses the "Delete" HTTP method, but I don't see a way to delete an entity with lava. I tried using the `{% sql %}` command to delete, but even that I was struggling to get working.

### Actual Behavior

Currently it's possible to create new entities using `{% modifyENTITY id:'0' %}`, but I don't believe there is support to delete entities, as well.

### Expected Behavior

Because it's possible to create an endpoint that utilizes the "Delete" HTTP method, it seems like there should be a way to delete entities within a lava application.

### Steps to Reproduce

Not sure how to show this since I don't think this is something that currently is expected to work.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

17.0.25

**Comment by jonedmiston** [comment]
We'll be working on this. Definitely see the need.

**Comment by bradencohen** [comment]
Added for the initial release of helix. Docs are here: https://helix.triumph.tech/lava-commands/delete-entity

**Comment by briankalwat** [comment]
@bradencohen will this be enabled along with the "Rock Entity Modify" lava command when configuring endpoints? 

For security reasons, I could definitely see the value in "Rock Entity Delete" being its own separate lava command to be explicitly enabled, but I realize that could have a lot of other implications.

<img width="994" alt="image" src="https://github.com/user-attachments/assets/4f47910e-8ccf-435d-9f24-4790c3e77dde">

**Comment by bradencohen** [comment]
@briankalwat it is a separate command with a "Rock Entity Delete" security setting.

**Comment by briankalwat** [comment]
Oh, okay amazing! I assume that will be included in the next (beta) release? Or would that be tied to a Rock update at some point?

**Comment by bradencohen** [comment]
This is included in the Helix package currently available in the Rock Shop @briankalwat .
