### ISSUE TITLE
Lava Shortcode for Helix - documentation and enhancements

### ISSUE THREAD

**Issue by stanalyst** [Triumph-Tech/Triumph-Helix#2]
### Description

None of this is really bugs ... more just related to clarity/accuracy of documentation and some enhancements for the shortcodes.

- The documentation for the shortcodes wasn't always consistent/clear. It seems like maybe some of the doc was just copied from the campus picker one?
- I did not confirm that this was true for all helix shortcodes, but there did not seem to be any way to suppress the Control Label from showing.
- For Defined Value Picker:
1. would love to be able to control # of columns when allowmultiple is true.
2. ability to display as Radio Button control vs Dropdown when allowmultiple is false (and also allow control of column count)
3. if displaydescriptions is true - if a given DefinedValue is missing its Description - then default to the Value

### Actual Behavior

n/a

### Expected Behavior

n/a

### Steps to Reproduce

n/a

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.6.9

**Comment by bradencohen** [comment]
Fixed for the initial release of Helix.
